export default {
    message: {
        'topPhone': '24-hour contact number',
        'navList': 'house',
        'news': 'NEWS',
        'entrust': 'ENTRUST',
        'problem': 'PROBLEM',
        'language': 'LANGUAGE',
        'CN': '中文',
        'EN': 'english',
        'KO': '한국어',
        //底部
        'corporateName':'corporate name',
        'junge':'junge housing',
        'representativeFigure':'representative figure',
        'TeamLeader':'Team Leader',
        'businessCircles':'Industrial and Commercial Registration No',
        'address':'address',
        'addressInfo':'Quasi real estate, 1f, 740 Jingren Road, Nandong District, Incheon City',
        'phone':'phone',
        'copyright':'2018 © junland。Photos, lists, communities - all information on the website is protected. Supported by junland housing',
        'aboutUs':'About Us',
        'Termsofservice':'Terms Of Service',
        'Privacystatement':'Privacy Statement',

        // 首页
        // 搜索框
        'AddressSearch':'Address Search',
        'MetroSearch': 'Metro Search',
        'seach': 'seach',
        'TransactionType':'Transaction Type',
        'SalesType': 'Sales Type',
        'ResidentialType': 'Residential Type',
        'fuzzySearch' : 'Address, subway, listing number, title',
        'selectCity': 'selectCity',
        'SearchBtn' : 'SEARCH',

        // 模块标题
        'Gotoarea':'GO TO AREA',
        'PopularProducts': 'POPULAR PRODUCTS',
        'whole': 'WHOLE',
        'room1':'ROOM 1',
        'room2':'ROOM 2',
        'room3':'ROOM 3',
        'room4':'ROOM 4',
        'compound':'COMPOUND',
        'recommend': 'RECOMMEND',
        'Aliexpress': 'INSTANT SALE',
        'TotalPrice': 'Total Price',
        'downPayments': 'Down Payments',
        'loan': 'LOAN',
        'TenThousandWon': 'Ten Thousand Won',
        'area': 'AREA',
        'floor': 'FLOOR',
        'NoDataYet' : 'No Data Yet',
        'CustomerComments':'CUSTOMER COMMENTS',
        'SeeMore': 'SEE MORE',
        'RealEstateNews': 'REAL ESTATE NEWS',
        'Partner': 'PARTNER',

        // 组件
        'LanguageSwitching': 'Are you sure to switch languages?',
        'Tips' : 'TIPS',
        'yes': 'YES',
        'no': 'NO',
        'home': 'HOME',
        // 房产列表页面
        'PleaseSelect': 'Please Select',
        'Reset': 'RESET',
        'MetroLine': 'Input Metro Line',
        'location': 'LC',
        'LargePicture': 'LP',
        'list': 'LIST',
        'between': 'between',
        'region':'region',
        'waterproof': 'waterproof',
        'ShowerRoom': 'ShowerRoom',
        'Photo': 'PHOTO',
        'type': 'TYPE',
        'transaction': 'TRANSACTION',
        'TitleAddress': 'TITLE & ADDRESS',
        'AdditionalInformation': 'ADDITIONAL INFORMATION',
        'Room':'ROOM',


// 新闻列表页
        'AllNews': 'All real estate news',
        'inputPlaceholder': 'Please enter the content',
        'LatestProperty': 'Latest Property',

        // 委托页面
        'entrust': 'ENTRUST',
        'tabFirst': 'Commission (buy / sell)',
        'tabSecond': 'Delegation list (QnA)',
        'RequiredArea': 'Required Area',
        'Price':'Price',
        'floorPrice':'floor Price',
        'ceilingPrice':'Ceiling Price',
        'CommissionType': 'Commission Type',
        'EstimatedTime': 'Estimated purchase / sale time',
        'accessTime': 'Date / time of access',
        'selectTile': 'Select date and time',
        'HouseSize': 'House size',
        'information': 'information',
        'name':'name',
        'eMail': 'eMail',
        'Display': 'Display',
        'demand': 'Demand',
        'Submit': 'Submit',
        'SerialNumber': 'Number',
        'buy':'BUY',
        'sell':'SELL',
        'SubmissionDate': 'Submission Date',

        // 常见问题
        'commonProblem': 'Common Problem',

        // 房产详情页
        'ArticleNo': 'Article No',
        'pis': 'Leave your contact information and we will contact you.',
        'essentialInformation': 'Essential Information',
        'AmountInformation': 'Amount Information',
        'LocationInformation': 'Location Information',
        'BuildingInformation': 'Building Information',
        'MoreInformation': 'More Information',
        'heating': 'HEATING',
        'NoHeating' : 'No Heating',
        'UrbanHeating': 'Urban Heating',
        'OptionInformation' :  'Option Information',
        'detailedDescription' :'detailed Description',
        'PhoneNumberOrEmail' :'Phone Number Or Email',
        'ConsultationContents' : 'Consultation Contents',
        'KeepInContact' : 'Keep In Contact',
        'MT1': 'supermarket',
        'CS2':'Convenience Store',
        'PS3':'kindergarten',
        'SC4':'school',
        'BK9':'bank',
        'CT1':'Entertainment facilities',
        'PO3':'Public institutions',
        'AT4':'scenic spot',
        'HP8':'hospital',
        'PopularRealEstate':'Popular Real Estate'
    }
}
