export default {
    message: {
        'topPhone': '24小时联系电话',
        'navList': '房产',
        'news': '新闻',
        'entrust': '委托',
        'problem': '常见问题',
        'language': '语言',
        'CN': '中文',
        'EN': 'english',
        'KO': '한국어',
        'select' : '请选择',
        'password': '密码',
        'autoLofin': '自动登录',
        'forgetPassword': '忘记密码',
        'loginBtn': '登录',
        'otherLoginWay': '其他方式登录',
        'register': '注册',
        'help': '帮助',
        'privacy': '隐私',
        'clause': '条款',
        'phone': '手机号',
        'code': '验证码',
        'getCode': '获取验证码',
    }
};
