export default {
    message: {
        // 头部
        'topPhone': '연중무휴문의', 
        'navList': '부동산',
        'news': '뉴스', 
        'entrust': '의뢰하기', 
        'problem': ' 자주 묻는 질문',
        'language': '언어', 
        'CN': '中文', 
        'EN': 'english', 
        'KO': '한국어',
        'toDay':'오늘 접속자수',
        'nowDay':'현재 접속자수',
        'losDay':'누적 방문자수',
        // --------------------------------------------------------
        //底部
        'corporateName':'이름', 
        'junge':'준 하우징', 
        'representativeFigure':'회사대표', 
        'TeamLeader':'최요원', 
        'businessCircles':'사업자 등록번호', 
        'address':'주소', 
        'addressInfo':'인천 남동구 경인로740 준하우징', 
        'phone':'전화번호', 
        'copyright':'2018@ junland housing,사진,메물,커뮤니티-사이트내 모든 정보는 보호됩니다.。Junland housing에서 지원', 
        'aboutUs':'회사소개', 
        'Termsofservice':'이용약관', 
        'Privacystatement':'개인정보취급방침', 

        // 首页 
        // 搜索框
        'AddressSearch':'주소 검색', 
        'MetroSearch': '지하철 검색', 
        'seach': '검색', 
        'TransactionType':'거래종류', 
        'SalesType': '매물종류', 
        'ResidentialType': '주택종류', 
        'fuzzySearch' : '주소 지하철,매물 번호,제목', 
        'selectCity': '도시 선택', 
        'SearchBtn' : '검색', 

        // 模块标题
        'Gotoarea':'지역별 바로가기', 
        'PopularProducts': '최신 매불', 
        'whole': '전체', 
        'room1':'1룸',
        'room2':'2룸',
        'room3':'3룸',
        'room4':'4룸',
        'compound':'복층', 
        'recommend': '추천', 
        'Aliexpress': '급매', 
        'TotalPrice': '분양가', 
        'downPayments': '실입주금', 
        'loan': '융자금', 
        'TenThousandWon': '만원', 
        'area': '면적', 
        'floor': '층수', 
        'NoDataYet' : '데이터 없음', 
        'CustomerComments':'고객 리뷰', 
        'SeeMore': '더보기', 
        'RealEstateNews': '부동산뉴스', 
        'Partner': '부동산싸이트', 

        // 组件
        'LanguageSwitching': '언어 바꾸겠습니다?',
        'Tips' : '힌트', 
        'yes': '네', 
        'no': '아니요', 
        'home': '홈페이지', 

        // 房产列表页面
        'PleaseSelect': '선택하세요', 
        'Reset': '재수정하기', 
        'MetroLine': '지하철노선 입력', 
        'location': '지도', 
        'LargePicture': '목록', 
        'list': '시계', 
        'between': '룸', 
        'region':'지방', 
        'waterproof': '방', 
        'family':'세대주 수',
        'ShowerRoom': '욕실', 
        'Photo': '사진', 
        'type': '유형', 
        'transaction': '거래', 
        'TitleAddress': '제목/주소', 
        'AdditionalInformation': '부가 정보', 
        'Room':'개인 실', 

        // 新闻列表页
        'AllNews': '부동산뉴스', 
        'inputPlaceholder': '내용입력', 
        'LatestProperty': '최신 매물', 

        // 委托页面 
        'entrust': '의뢰하기', 
        'tabFirst': '구하기 매수/팔다', 
        'tabFirst': '구하기（사다）',
        'tabSale': '구하기（팔다）',
        'tabSecond': '위탁(QNA)', 
        'RequiredArea': '원하는 지역', 
        'Price':'가격', 
        'floorPrice':'최저 가격', 
        'ceilingPrice':'최고 가격', 
        'CommissionType': '위탁 유형', 
        'EstimatedTime': '구매 얘정/판매 시간', 
        'accessTime': '방문 날짜/ 시간', 
        'selectTile': '시간 선정', 
        'HouseSize': '면적', 
        'information': '정보', 
        'name':'이름', 
        'eMail': '이메일', 
        'Display': '전열 여부', 
        'demand': '요청사항', 
        'Submit': '등록', 
        'SerialNumber': '번호', 
        'buy':'구매', 
        'sell':'판매', 
        'SubmissionDate': '등록 시간', 

        // 常见问题 
        'commonProblem': '자주 묻는 질문' ,
        
        // 房产详情页
        'ArticleNo': '상품id', 
        'pis': '연락처를 남겨주시면 바로 연락드리겠습니다.',
        'essentialInformation': '기본 정보', 
        'AmountInformation': '금액 정보', 
        'LocationInformation': '주소 정보', 
        'BuildingInformation': '건축 정보', 
        'MoreInformation': '추가정보', 
        'heating': '가열', 
        'NoHeating' : '난방 없음', 
        'UrbanHeating': '도시 난방', 
        'OptionInformation' :  '옵션 정보', 
        'detailedDescription' :'상세 설명', 	
        'PhoneNumberOrEmail' :'전화번호 및 이메일', 
        'ConsultationContents' : '상담대용', 
        'KeepInContact' : '연락 유지', 
        'MT1': '슈퍼', 
        'CS2':'편의점', 
        'PS3':'유치원', 
        'SC4':'학교',  
        'BK9':'은행', 
        'CT1':'유락시설', 
        'PO3':'공공기관', 
        'AT4':'명소', 
        'HP8':'의원',  
        'PopularRealEstate':'인기 부동산',
        // 手机
        "lookMapList": '이 지역 매물보기',
        "call": ' 전화하기'
    }
};
