export default {
    message: {
        'topPhone': '24-hour contact number',
        'navList': 'house',
        'news': 'NEWS',
        'entrust': 'ENTRUST',
        'problem': 'PROBLEM',
        'language': 'language',
        'CN': '中文',
        'EN': 'english',
        'KO': '한국어',
        'select' : 'select',
        'loginAccount': 'Credentials',
        'loginByPhone': 'Mobile number',
        'account': 'Account',
        'password': 'password',
        'autoLofin': 'Remember me',
        'forgetPassword': 'Forgot your password?',
        'loginBtn': 'Login',
        'otherLoginWay': 'Sign in with',
        'register': 'Sign up',
        'help': 'help',
        'privacy': 'privacy',
        'clause': 'clause',
        'phone': 'Mobile Number',
        'code': 'Verification code',
        'getCode': 'Get code',
    }
}
