export default {
    message: {
        'topPhone': '연중무휴 문의',
        'navList': '매물검',
        'news': '뉴스',
        'entrust': '의뢰하기',
        'problem': '문제',
        'language': '언어',
        'CN': '中文',
        'EN': 'english',
        'KO': '한국어',
        'select' : '선택하십시오',
        'loginAccount': 'Credentials',
        'loginByPhone': 'Mobile number',
        'account': 'Account',
        'password': 'password',
        'autoLofin': 'Remember me',
        'forgetPassword': 'Forgot your password?',
        'loginBtn': 'Login',
        'otherLoginWay': 'Sign in with',
        'register': 'Sign up',
        'help': 'help',
        'privacy': 'privacy',
        'clause': 'clause',
        'phone': 'Mobile Number',
        'code': 'Verification code',
        'getCode': 'Get code',
    }
}
