export default {
    message: {
        // 头部
        'topPhone': '24小时联系电话',
        'navList': '房产',
        'news': '新闻',
        'entrust': '委托',
        'problem': '常见问题',
        'language': '语言',
        'CN': '中文',
        'EN': 'english',
        'KO': '한국어',
        // --------------------------------------------------------
        //底部
        'corporateName':'名称',
        'junge':'俊阁家园',
        'representativeFigure':'代表人物',
        'TeamLeader':'组长',
        'businessCircles':'工商登记号',
        'address':'地址',
        'addressInfo':'仁川市南东区京仁路740 1层准房地产',
        'phone':'电话',
        'copyright':'2018 © junland。照片、列表、社区 - 网站上的所有信息都受到保护。由junland housing提供支持',
        'aboutUs':'关于我们',
        'Termsofservice':'服务条款',
        'Privacystatement':'隐私声明',

        // 首页
        // 搜索框
        'AddressSearch':'地址搜索',
        'MetroSearch': '地铁搜索',
        'seach': '搜索',
        'TransactionType':'交易类型',
        'SalesType': '销售类型',
        'ResidentialType': '住宅类型',
        'fuzzySearch' : '地址、地铁、挂牌号，标题',
        'selectCity': '选择城市',
        'SearchBtn' : '搜索',

        // 模块标题
        'Gotoarea':'前往地区',
        'PopularProducts': '热门产品',
        'whole': '全部',
        'recommend': '推荐',
        'Aliexpress': '速卖',
        'TotalPrice': '总价',
        'downPayments': '首付',
        'loan': '贷款',
        'TenThousandWon': '万韩元',
        'area': '面积',
        'floor': '楼层',
        'NoDataYet' : '暂无数据',
        'CustomerComments':'顾客评论',
        'SeeMore': '查看更多',
        'RealEstateNews': '房地产新闻',
        'Partner': '合作方',

        // 组件
        'LanguageSwitching': '确定切换语言吗?',
        'Tips' : '提示',
        'yes': '是的',
        'no': '不了',
        'home': '首页',

        // 房产列表页面
        'PleaseSelect': '请选择',
        'Reset': '重置',
        'MetroLine': '输入地铁线路',
        'location': '定位',
        'LargePicture': '大图',
        'list': '列表',
        'between': '间',
        'region':'区域',
        'waterproof': '防水',
        'ShowerRoom': '浴室',
        'Photo': '照片',
        'type': '类型',
        'transaction': '交易',
        'TitleAddress': '标题/地址',
        'AdditionalInformation': '附加信息',
        'Room':'室',

        // 新闻列表页
        'AllNews': '所有房地产新闻',
        'inputPlaceholder': '请输入内容',
        'LatestProperty': '最新房产',

        // 委托页面
        'entrust': '委托',
        'tabFirst': '委托（买/卖）',
        'tabSecond': '委托列表（QNA）',
        'RequiredArea': '所需区域',
        'Price':'价格',
        'floorPrice':'最低价格',
        'ceilingPrice':'最高价格',
        'CommissionType': '委托类型',
        'EstimatedTime': '预计购买/卖时间',
        'accessTime': '访问日期/时间',
        'selectTile': '选择日期时间',
        'HouseSize': '房屋大小',
        'information': '信息',
        'name':'姓名',
        'eMail': '邮箱',
        'Display': '是否显示',
        'demand': '需求',
        'Submit': '提交',
        'SerialNumber': '序号',
        'buy':'购买',
        'sell':'出售',
        'SubmissionDate': '提交时间',

        // 常见问题
        'commonProblem': '常见问题',
        
        // 房产详情页
        'ArticleNo': '货号',
        'pis': '留下您的联系方式，我们会与您联系。',
        'essentialInformation': '基本信息',
        'AmountInformation': '金额信息',
        'LocationInformation': '地点信息',
        'BuildingInformation': '建筑信息',
        'MoreInformation': '更多信息',
        'heating': '加热',
        'NoHeating' : '无供暖',
        'UrbanHeating': '城市供暖',
        'OptionInformation' :  '选项信息',
        'detailedDescription' :'详细说明',
        'PhoneNumberOrEmail' :'电话号码或邮箱',
        'ConsultationContents' : '咨询内容',
        'KeepInContact' : '保持联系',
        'MT1': '超级市场',
        'CS2':'便利店',
        'PS3':'幼儿园',
        'SC4':'学校',
        'BK9':'银行',
        'CT1':'娱乐设施',
        'PO3':'公共机构',
        'AT4':'景点',
        'HP8':'医院',
        'PopularRealEstate':'热门房产'
    }
};
